### ISSUE TITLE
Ensure VS Code Desktop can reconnect to workspace after timeout

### ISSUE THREAD

**Issue by tysonrm** [gitpod-io/gitpod#10288]
## Is your feature request related to a problem? Please describe
Yes, having selected local IDE, when workspace times out, IDE can't reconnect (because it doesn't know to restart the workspace.)

## Describe the behaviour you'd like
A customization to VSCode and other popular IDEs that restarts the workspace before attempting to reconnect to it.

## Describe alternatives you've considered
A ping to prevent the workspace from timing out.

I'm very busy but it might be worth it to contribute if I get some guidance on this. Love your platform. Excellent work!

**Comment by JcdeA** [comment]
A solution to this issue may be something where a dialog pops up when a workspace times out, similar to how GitHub Codespaces does it.

Just having a button to restart the workspace easily would be great (#4782 may be related to this solution).

**Comment by loujaybee** [comment]
Thanks for raising @tysonrm ! 🙏 

It won't be solved by, but relates to: 

- https://github.com/gitpod-io/gitpod/issues/9038

**Comment by narkeeso** [comment]
Is there a workaround for this for now? Is there a way to extract the password from the new workspace link and then give it to vscode to just resume?

**Comment by david-bakin** [comment]
> Is there a workaround for this for now? Is there a way to extract the password from the new workspace link and then give it to vscode to just resume?

I tried getting the password out of the ssh link from the dashboard and providing that to the dialog asking for the password - but it didn't work.  In fact, it looked from the prompt in the dialog that somehow the password (or what I thought was the password, between `#` and `@`) was incorporated into the ssh remote extension's idea of the hostname.  I'd _really_ like to be able to do this.

**Comment by jeanp413** [comment]
@narkeeso @david-bakin with pre-release version of `gitpod-desktop` extension and  configuring your [ssh keys in Gitpod](https://gitpod.io/keys) it won't ask you for a password anymore when reconnecting after a workspace restart
![image](https://user-images.githubusercontent.com/25115070/179345479-c330312f-db0c-461a-9314-ff6c4a74d7b9.png)

**Comment by david-bakin** [comment]
> @narkeeso @david-bakin with pre-release version of `gitpod-desktop` extension and configuring your [ssh keys in Gitpod](https://gitpod.io/keys) it won't ask you for a password anymore when reconnecting after a workspace restart

Took me a second to figure it out - you still get a "enter your password prompt" at the top of VSCode but you ignore it and click the "reconnect window" button down at the bottom right - and your restarted workspace hooks right up.  👍

**Comment by jeanp413** [comment]
> you still get a "enter your password" prompt at the top of VSCode

Good catch @david-bakin I created an issue for that bug https://github.com/gitpod-io/gitpod/issues/11428

**Comment by loujaybee** [comment]
As @jeanp413 mentioned, if you're using the SSH Gateway with an uploaded SSH key VS Code should be able to reconnect when you start / restart the workspace (see: [related docs](https://www.gitpod.io/docs/ides-and-editors/vscode#reconnect-to-vs-code-desktop)). 

To configure: 
1. Set `gitpod.remote.useLocalApp` to `false` in your settings
2. [Upload an SSH Key to Gitpod ](https://www.gitpod.io/docs/configure/ssh#upload-an-ssh-key-to-gitpod)

This doesn't entirely solve the problem as you'll still have to go to the workspace stop page or dashboard to restart the workspace, and it indeed would be nice if VS Code could wake up your workspace for you. However, I think the other suggestions are captured in: 

Prompt for users when workspace stopping:
- https://github.com/gitpod-io/gitpod/issues/11263

Ensure user can restart workspace from within VS Code:
- https://github.com/gitpod-io/gitpod/issues/9221

So I will close this issue 🙏

**Comment by iojcde** [comment]
Still doesn't work when the cluster changes :(

**Comment by loujaybee** [comment]
Hey @iojcde thanks for raising / the feedback, this is a known current limitation, and is raised here: 

- https://github.com/gitpod-io/gitpod/issues/11355

If you have any other thoughts, would like to track the issue or upvote to raise more visibility 🙏
