### ISSUE TITLE
Gitpod is unstable in the US

### ISSUE THREAD

**Issue by RDIL** [gitpod-io/gitpod#1075]
its down

**Comment by MadnessTabletop** [comment]
Can verify, can't login.

**Comment by HSSANT** [comment]
> Can verify, can't login.
> 
> To elaborate, I successfully get routed to Github for the oauth. But when I get pushed back to gitpod I get a 504.

Im getting same error here.

**Comment by RDIL** [comment]
If any gitpod staff are online, please help, I have things I need to get done

cc @jankeromnes @svenefftinge @AlexTugarev

**Comment by alesanchezr** [comment]
😢

**Comment by MadnessTabletop** [comment]
Some further info.

When trying to login the following call returns a 404.

https://gitpod.io/api/refresh-login

**Comment by RDIL** [comment]
> Some further info.
> 
> When trying to login the following call returns a 404.
> 
> https://gitpod.io/api/refresh-login
It's not even responding for me

**Comment by meysholdt** [comment]
it's all back up again. Please reopen if problems persist.

**Comment by jankeromnes** [comment]
Many thanks for reporting this unfortunate issue. We hope that it didn't cause you too big of a disruption, and sincerely apologize that Gitpod didn't work. This should really almost never happen.

Also, we've looked into what may have caused this, and here is what we found FYI:

At first we thought this was somehow related to the occasional network instabilities we recently started noticing in Google Cloud (it's sometimes causing some workspaces to get into state `UNKNOWN`, for example). However, there was no such instability in US or EU around the reported downtime.

However, given that several workspaces were reported as "unhealthy", and that almost all services did restart at least once, we strongly suspected a network instability of some kind.

Then we found that GitHub's API response times, which usually hover around 1 second, slowed down to over 10 seconds around 17:12 UTC, and then peaked at 370+ seconds a few times around 18:22 UTC. Around 19:00 UTC it was consistently slow. However, https://www.githubstatus.com/ doesn't show any downtime during that time, so we're still not quite sure what went wrong exactly, but since these delays seemed extreme we hope that this was an isolated incident.

**Comment by alesanchezr** [comment]
Thank you @jankeromnes!

**Comment by RDIL** [comment]
Hey @jankeromnes,
While gitpod is back up, I'm now experiencing a lot of nginx 500 errors and its being super slow overall.

**Comment by jankeromnes** [comment]
@RDIL that sounds worrisome. Where do you see these 500 errors? (E.g. when attempting which Gitpod action or trying to open what type of URL?)

**Comment by RDIL** [comment]
Its happening for in-ide image previews and trying to open react development servers so far

**Comment by HSSANT** [comment]
Hello @jankeromnes  , the same errors from yesterday started again. The ngxinx 500 errors are showing when i try to open my application in port 8000 for example, from "open ports" tab.

Could you please check?

**Comment by jankeromnes** [comment]
Thanks a lot for reporting this again. We're looking into it.

**Comment by davelavoie** [comment]
Just to confirm I'm having the same issue for the last hour or so. This is the same issue I was having yesterday. I'm getting the following error when trying to browse the site of the workspace I was working on (this is a plain WordPress install with no plugin installed):

> 500 Internal Server Error
> nginx/1.14.1

No workspaces are shown either on my Gitpod account...

![image](https://user-images.githubusercontent.com/3408028/72368655-84f37f00-36cc-11ea-97f9-6770182e9530.png)

**Comment by BobHerold** [comment]
I'm also getting the same errors and problems as mentioned above;   500 Internal Server Error;   and the workspace will not open up;   also when I could get in,   when I checked my Access Control settings, all of my "permissions" had been unchecked!   Rechecked them all, but still unable to access workspaces

**Comment by BobHerold** [comment]
It was fine this AM (EST, US);  went to lunch, when I came back about 12:30 PM, unable to access

**Comment by BobHerold** [comment]
I'm currently accessing once again;   I've lost about 3 hours over the last 2 days,  I hope this "unreliability" ends.

**Comment by Kreyren** [comment]
So is this GitHub's fault through API being unavailable or is this issue with gitpod network connection to the world?

**Comment by Kreyren** [comment]
Also the outage was not reported on https://status.gitpod.io/ -> assuming insufficient detection

**Comment by jankeromnes** [comment]
I think there are several different issues here:

- Unable to log into Gitpod due to Error 504
- Unable to preview a workspace port due to Nginx Error 504

I apologize for our slow response time on these issues, as part of the team is currently off on holidays, and I have limited experience with issues like these. We'll do our best to understand and fix these instability issues as soon as possible.

For now, this issue only seems to affect the `us02` region (please let me know if you think this is not the case).

We'll investigate both issues mentioned above. Please comment if you see other issues as well, ideally with precise error codes + screenshots + URLs when possible.

We'll also deploy a minor Gitpod update to production later today, in the hopes that this can also help reset anything bad in the current deployment.

**Comment by jankeromnes** [comment]
> Unable to preview a workspace port due to Nginx Error 500

Yesterday, we saw some port control errors in our logs where our workspace manager complained about unknown workspace IDs. This is likely related.

**Comment by jankeromnes** [comment]
We've found a RabbitMQ process eating up all available CPU in the US (that's a message queue we use to communicate data between services). Stopping & restarting it didn't help, so it's likely something else in our US cluster that's constantly creating new queues, overloading the message queue system and potentially causing the degraded Gitpod service.

Our current suspect is a Jaeger pod (which we use for start-up time performance monitoring, ironically) that was stuck in a crash-restart-loop.

**Comment by RDIL** [comment]
Have you tried turning the whole cluster off and back on again? 🤣

**Comment by jankeromnes** [comment]
We're about to release a fresh Gitpod deployment (with unrelated minor fixes) to all regions. We hope that this can reset the bad state that the US cluster got into recently.

We've also extensively investigated several potential root causes, and are working on longer-term fixes to prevent this situation from happening again.

**Comment by RDIL** [comment]
Got it.  Thanks!

@Kreyren it was a *joke* 🙁

**Comment by jankeromnes** [comment]
Update: The Gitpod deployment has been postponed to tomorrow 05:00 UTC, in order to deploy at a time when there is less load on the system.

**Comment by alesanchezr** [comment]
THank you!

**Comment by RDIL** [comment]
Jan its happening again 😭

**Comment by MrArturtleNSCDS** [comment]
GitPod seems to be down again. Same issue as two days ago. Connections are being disposed.

**Comment by filipedeschamps** [comment]
Same here 👍

**Comment by HSSANT** [comment]
same here
@jankeromnes  could you please check? we are all stucked here with all these errors.

**Comment by adriusg** [comment]
@jankeromnes please :(  we need help. We are stopped.

**Comment by jankeromnes** [comment]
Wow, so sorry everyone for the terrible experience yesterday. 😞 Our monitoring looks quite bad, the US cluster really didn't hold up to the load. And since we're based in Europe, with our staff pretty thinned out at the moment, we couldn't respond in time.

On a slightly more positive note, this morning we were able to deploy a fresh Gitpod to all regions. We'll also monitor the US region very closely today, in order to quickly catch any performance problems and react accordingly. We want this to never happen again.

**Comment by RDIL** [comment]
Sick!  Thanks @jankeromnes :D

**Comment by jankeromnes** [comment]
Update: We've identified that the service disruption was caused by a few runaway cluster management services (likely Jaeger in combination with Prometheus and RabbitMQ) which caused a denial-of-service on other critical systems nearby, leading to the overall degraded Gitpod service observed in the US region.

On this graph, we can see sustained high CPU load in various US cluster management services, which correlates with the instability window:

<img width="1349" alt="Screenshot 2020-01-16 at 09 29 46" src="https://user-images.githubusercontent.com/599268/72508605-441f7580-3846-11ea-985e-79d110d53620.png">

Earlier this morning we were able to finally resolve this extreme load situation by deploying a hotfix, as can be seen toward the end of the graph. The instability problems should now be gone.

We're also auditing further monitoring data in order to better understand the symptoms and root causes of these extreme loads, and we will have an internal post-mortem meeting in order to put in place mitigations to prevent such a long outage from happening again.

Again, we're extremely sorry about the disruption that this caused you. We will make any efforts necessary to ensure that Gitpod is always stable and fast, and that our team can respond quicker and more effectively at the first sign of trouble.

P.S. https://status.gitpod.io/ is now up-to-date again. Thank you for reporting that it wasn't.

**Comment by Kreyren** [comment]
> We've identified that the service disruption was caused by a few runaway cluster management services (likely Jaeger in combination with Prometheus and RabbitMQ) which caused a denial-of-service on other critical systems nearby,

It may be worth it to consider MuQSS scheduler from Con Kolivas (http://ck.kolivas.org/patches/muqss/) and some process priority management so that in case of this happening again the scheduler would be able to scale the load without affecting critical processes and limiting processes that are set to be less important.

Compared to Fair scheduler that halts on load above 100% and doesn't scale as good (at least on my systems)

**Comment by RDIL** [comment]
@jankeromnes @meysholdt its happening again 😠 reeeeeeeee

**Comment by Kreyren** [comment]
I wonder why is US02 the only affected cluster.

Speaking from experience and assuming the symptoms I would guess that overheating might be a possible cause?
Meaning causes like old thermal paste or dust buildup, because hosting is incompetent? or maybe power input has micro-shortages that confuse scheduler or doesn't provide sufficient power at critical times that triggers partial fails safe?

I don't think that mensioned system monitors would cause this since they are generally resource friendly.

**Comment by MadnessTabletop** [comment]
On my end the system seems to be working. Unlike before, I'm able to log in. Loading up a workspace takes a bit of time, but otherwise things seem to be working.

**Comment by HSSANT** [comment]
now all my workspace are throwing a error
**Request startWorkspace failed with message: Not connected to message bus**

The whole week gitpod its down every single day.

**Comment by jankeromnes** [comment]
Thank you for the reports, this seems to be a different issue, but it also affects only the US region for some reason.

We've implemented a temporary fix. Please try again. Will investigate more on Monday.

**Comment by HSSANT** [comment]
yes its stables until now. Thanks @jankeromnes

**Comment by Kreyren** [comment]
> but it also affects only the US region for some reason.

Any news from the hosting then? Seems like their issue with possible (D)DOS ? But that would be obvious on the network graph..

**Comment by jankeromnes** [comment]
@Kreyren unclear. `us01` also had issues, which is why we moved to `us02` in the first place. We may need to move again if the root cause is indeed something with the datacenter

**Comment by RDIL** [comment]
At this point, can you just add error handling that re-routes us to the UK or something?

**Comment by jankeromnes** [comment]
@RDIL Good idea. We've done that manually in the past and could potentially automate it.

**Comment by Kreyren** [comment]
> but it also affects only the US region for some reason.

Response delay from US to UK would be unusable i would assume

**Comment by Kreyren** [comment]
I would also recommend a blockchain, but configuring it to be reliable is usually a challenge.

**Comment by RDIL** [comment]
NO NO NO its happening again 😭

**Comment by HSSANT** [comment]
😭    😭     😭     😭     😭     😭     😭     😭     😭     😭     😭
 😭     😭     😭     😭     😭     😭     😭     😭     😭     😭

every day its down

**Comment by RDIL** [comment]
Jan when is everybody coming back?

**Comment by jankeromnes** [comment]
@RDIL @HSSANT The team is now complete again. Also, we've just deployed a hotfix to better handle the "micro network outages" seen in the US cluster. However, something seems broken since the deployment, and we're looking into it.

Normally, deploying small hotfixes like these should be really seamless, and it's never caused such outages before. We're trying to fix this one as fast as possible, and since this is quite scary, I think we'll change our hotfix deployment policy (e.g. only deploy during the night, in order to limit the impact caused by any unforeseen breakages). Also, it's not normal that the US cluster is so fragile at this moment. We'll look into making it more robust as well.

**Comment by geropl** [comment]
@RDIL @HSSANT It should be back to normal now. Can you confirm?

**Comment by HSSANT** [comment]
Up and running. thanks

**Comment by RDIL** [comment]
Its back :((((((((((((((((((((((((

**Comment by RDIL** [comment]
aaaand its happening again

fun

**Comment by RDIL** [comment]
I made a detailed diagram of how we could in theory fix the problem for now:

![Diagram](https://user-images.githubusercontent.com/34555510/72929797-89511500-3d28-11ea-82c8-7168b3a72b97.png)

**Comment by jankeromnes** [comment]
Really sorry about this sporadic, annoying problem. Permanently resolving this is currently our top focus, and we're making progress investigating the root cause(s). We have a few promising theories, so I hope to bring good news very soon. Meanwhile, we try to quickly restore service as quickly as possible whenever it occurs. I'll keep you updated on our progress.

**Comment by JesterOrNot** [comment]
Re-Opening due to the fact that this is still going on

**Comment by jankeromnes** [comment]
Thanks @JesterOrNot!

But I think it would be better to track the specific Error 500 in #1128.

To me this issue was more about the severe instability we saw last week, and mentions several other problems (workspace state "Unknown"; Error 504 on login; "Connection got disposed"; etc.) that are now fixed.

We're not seeing denial-of-service level loads since last week, so this Error 500 is something else.

**Comment by raghubetina** [comment]
This is still occurring for us. It occurred for us on Monday the 13thin exactly the same way — everything was fine from ~6am central onwards, but precisely at 8:30am the issue started occurring (unfortunately for us, that's when classtime begins).

**Comment by RDIL** [comment]
Yeah its happening right now

**Comment by jankeromnes** [comment]
Thanks @raghubetina and @RDIL for reporting this. We're aware of a new incident in the US region, and are trying to understand the problem and restore service as fast as possible.

**Comment by RDIL** [comment]
Maybe now would be a good time to try ![](https://user-images.githubusercontent.com/34555510/72929797-89511500-3d28-11ea-82c8-7168b3a72b97.png)

**Comment by jankeromnes** [comment]
This specific problem seems to be the `Error 504`, so let's track it in #1151 instead (we'll post any updates there).
