### ISSUE TITLE
Simpler self-hosting

### ISSUE THREAD

**Issue by mlvzk** [gitpod-io/gitpod#10916]
## Is your feature request related to a problem? Please describe

Self-hosting Gitpod on Kubernetes is expensive and hard.

## Describe the behaviour you'd like

I'd like to be able to self-host development machines on Gitpod without setting up a Kubernetes cluster. For personal use cases, Kubernetes clusters are expensive and complex.

It would be nice if I could rent a VPS, install Docker on it and connect it to Gitpod, so that I can use it for new workspaces.

This is similar to how self-hosting custom Github Actions runners works, if you use something like https://github.com/myoung34/docker-github-actions-runner

## Describe alternatives you've considered

Setting up a Kubernetes cluster on the cloud - too expensive, $70 or more just for the control plane.

Setting up a K3s cluster on a VPS - offline workspaces are stored on the VPS, if you switch between workspaces a lot you will need a lot of disk storage on your VPS.

Both alternatives are harder to maintain than what I'm proposing.

**Comment by axonasif** [comment]
Hey @mlvzk 👋 
Nice that you asked, recently we released a new installation mode.
See https://www.gitpod.io/docs/self-hosted/latest/preview-install

**Comment by mlvzk** [comment]
> Hey @mlvzk 👋 Nice that you asked, recently we released a new installation mode. See https://www.gitpod.io/docs/self-hosted/latest/preview-install

Hello, thank you for your reply. "Preview Install" seems to only be useful for trying out self-hosted Gitpod before setting it up "properly". It has the same problems as setting up K3s on a VPS and installing Gitpod there.

I want to only self-host compute, not storage (of offline workspaces or prebuilds).
I would still see all my workspaces on Gitpod.io, but when I start a workspace, it would run on the machines I provided.
Ideally, the experience would be identical to running on machines hosted by Gitpod, with the web editor and public ports still being on Gitpod's domain.

**Comment by MrSimonEmms** [comment]
This sounds like something akin to [GitLab Runners](https://docs.gitlab.com/runner/) - this isn't self-hosted _per se_, but you provide the compute power and anything running on there doesn't count towards your usage allowance. The setup is a simple bash script (or Docker/Kubernetes if you want) that connects to your account.

AFAIK, this is not something under consideration at the moment but a good feature request. As it's to do with gitpod.io, it would be handle by the Workspace Team rather than Self-Hosted

**Comment by atduarte** [comment]
Thanks for the suggestions @mlvzk! 

At Gitpod we are focused on providing ephemeral development environments, and therefore the Kubernetes cluster requirement. For that reason, we currently have no plans to support what you proposed. Would you invite you to use SaaS where you have no maintenance and is more cost efficient.
