### ISSUE TITLE
[image-builder] Support for `self-signed` certificates

### ISSUE THREAD

**Issue by mrsimonemms** [gitpod-io/gitpod#11811]
### Context

`self-signed` support for Gitpod was only added in EKS. This works by loading the custom CA certificate in each pod but the same also has to be loaded into `containerd` for the registry image pulls to work for any workspace creations to work.

With the gitpod-eks-guide, We built custom AMI images where we [update containerd config](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/ami/files/gitpod/containerd.toml#L28), and [restart it ahead](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/ami/scripts/shared/docker.sh#L77) to make this work. As we don't have something similar for GKE, and AKS, `self-signed` Gitpod was never supported there.

### Current Issue

The new single cluster reference architecture guides (& the terraform scripts), don't [use the custom AMI images for EKS](https://github.com/gitpod-io/gitpod/issues/12979) yet.  Moving to custom AMI images **does not also seem to be a great solution, as it's against some customer policies.**

Which means `self-signed` Gitpod is **now not supported in any cloud provider**. This includes the previously known GKE, AKS and now the newly changed EKS guides.

The following issue is thrown whenever a workspace is created:

![Screenshot 2022-09-15 at 9 38 47 AM](https://user-images.githubusercontent.com/7892868/190312055-0e96cfc9-257b-49c7-9f8e-1f54b0b7a1ff.png)

## Steps to reproduce

The same above behaviour can be verified by running the infra test werft jobs using the following command on a workspace with #12910 changes: (EKS here, but GKE should also work too)

```
werft run github -f -s .werft/installer-tests.ts -j .werft/eks-installer-tests.yaml -a debug=true -a self-signed=true -a skipTests=true -a preview=true
```

## Expected behaviour

Customers want to use self signed instances of Gitpod internal to their environments, where they expect their clients to have added the trust root. This means `containerd` on the nodes pulling images from the `registry-facade` without any trust errors.

## Definition of Done

Our workspace components should support self-signed TLS certs across cloud providers, without having to do custom built AMI images (which had customer concerns).

Also, the reference architecture and product compatibility matrix should be updated, too.

## Anything else

**Warning**: there could be more than just image-builder that is unable to support self-signed certs.

**Warning**: cloud providers will have different versions of containerd and the kernel

<details><summary>Previous Issue Description</summary>

When working on #11666, it was noted that there are two issues at play - this one is specifically about the problems with making GKE aware of custom CA certs

There are a couple of potential workarounds available (see https://github.com/gitpod-io/gitpod/pull/11666#issuecomment-1199966792) which may be helpful.

There are been a ticket raised with Google about this - see https://github.com/gitpod-io/gitpod/pull/11666#issuecomment-1200861230

/details>

**Comment by Pothulapati** [comment]
So, More context on this issue:

With the gitpod-eks-guide, We built custom AMI images where we [update containerd config](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/ami/files/gitpod/containerd.toml#L28), and [restart it ahead](https://github.com/gitpod-io/gitpod-eks-guide/blob/main/ami/scripts/shared/docker.sh#L77) to make this work.  As we don't have something similar for GKE, and AKS, `self-signed` Gitpod was never supported there.

This [isn’t part of single-cluster reference arch yet](https://github.com/gitpod-io/gitpod/issues/12979) yet, and hence #12979 was raised accordingly. We could (and might for now) fix this by moving to the custom AMI images, but we would still have to look a fix for GKE and AKS customers.

**Comment by Pothulapati** [comment]
Updated the issue to reflect the current behaviour (i.e removed gke mention) as it applies to all cloud providers in the reference architectures right now.

**Comment by Pothulapati** [comment]
FYI: Updated the issue description to include information from the comments that I had here, and deleted them to prevent confusin.

**Comment by mrzarquon** [comment]
I believe we addressed this in our ALB advanced guide - https://www.gitpod.io/docs/self-hosted/latest/advanced/eks-with-alb-and-nlb#0-node-configuration

**Comment by Pothulapati** [comment]
With https://github.com/gitpod-io/gitpod/issues/12979#event-7474205110, We made `self-signed` work on EKS single-cluster reference architecture guides! This is done by adding the script that @mrzarquon suggested, as `post_bootstrap_user_data`.

Keeping this issue open as support GKE and AKS still isn't there due to the lack of similar options in those environments.

**Comment by hkjolhede** [comment]
Do you have any suggestions for using self-signed certificates on K3s clusters? I have an external HAProxy that does the TLS termination, so I have setup the cluster to use self-signed certificates internally. Everything works except for the registry, meaning I can't build any workspaces.

**Comment by hkjolhede** [comment]
@MrSimonEmms Thank you! That worked like a charm.
