### ISSUE TITLE
Cannot create new files

### ISSUE THREAD

**Issue by stefdworschak** [gitpod-io/gitpod#1573]
Hi all,

Some of our students have reported issues in creating new files in their workspaces' directories. 

Does not work:
- Use the "File" - "New File" menu
- Right-click "New File"

Does work:
- Using touch from the terminal

Could you please have a look at this issue as soon as possible?

Thanks,
Stefan

**Comment by bravoalpha79** [comment]
Possibly related, a suddenly not-working HTML tag auto-complete has been reported by at least two users.

**Comment by Saharalnoor** [comment]
Hi! I am experiencing the same issue in gitpod.

**Comment by irinatu17** [comment]
I have the same issue, as well as not able to create a new folder.

**Comment by Decline-of-Mind** [comment]
I am unable to create any new files or folders, as well as HTML autocomplete not working. If I type .thisclass and press tab, it only indents me further. It doesn't create the div with my class.

**Comment by Sparkplug84** [comment]
I also had similar issues today. Unable to create new files or folders using the menu. Also my environment problems and warnings were not visible any more.

**Comment by AlexiaDelorme** [comment]
I am currently experiencing an issue with the "Format document" command that is no longer working on any of my gitpod workspaces.

**Comment by corneliusludmann** [comment]
Thanks you all for reporting. Unfortunately, I'm not able to reproduce this. Could you please provide some more information:

1. Was it a newly created workspace or did you re-start an existing workspace? In case of the latter: When was the workspace created (see https://gitpod.io/workspaces/ – top right corner of the workspace item)?
2. Could you provide a workspace instance ID where this happens (the thing at the beginning of the URL in the browser like `af4bcca2-87ad-4223-be37-66c7dc79cf02`)?
3. Could you probably share a workspace snapshot where this happens (e.g. via support@gitpod.io as long as here are no confidential information in this workspace)?

**Comment by AlexiaDelorme** [comment]
Hi Cornelius, 

Thanks for getting back to us.
1. I re-started an existing workspace. My workspace was created 3 months ago.
2. My workspace instance ID: `da314b55-5d5b-43c9-86b7-56ec4a4196d4`
3. I have sent the screenshot by email.

Thanks and regards,
Alexia

**Comment by GlobetrotterG** [comment]
Same here. I am trying to add a folder, and wouldn't let me. Also, when I try to use the auto-tag feature, it wouldn't let either. So I had to write the whole code.

**Comment by NgiapPuoyKoh** [comment]
Gitpod workspace not behaving consistently (files not saved and browser run behavioir not consistent)  during the past 10 hours. Very frustrating  had to stop and restart several times.  https://d552dc35-3c89-47ef-abb1-2f9bf4495be5.ws-eu01.gitpod.io/ fincally at this time unable to start the workspace. Also ran into the following issue during the last session
![Errors](https://user-images.githubusercontent.com/61414348/83696536-b06afd80-a5ca-11ea-8ebb-ea1b0c8760d0.jpg)

**Comment by eldowling** [comment]
I don't know if this issue I'm having is related, but when I try to test my login page by using an invalid password I get this error:
`jinja2.exceptions.UndefinedError: 'form' is undefined`

This used to work without issue, so when I look at my app.py I have seen lots of imports have failed, like this:
![image](https://user-images.githubusercontent.com/43374354/83725162-64a36d00-a639-11ea-93ef-4d43df6b6c9e.png)

**Comment by stefdworschak** [comment]
@corneliusludmann is there any update on this issue and do we have an ETA for when this might be fixed? Or do you need any additional information?

**Comment by corneliusludmann** [comment]
@jankeromnes has taken over the investigation. Since we are not able to reproduce this we need someone who can share his/her workspace with us, I guess. @jankeromnes can tell more ...

**Comment by jankeromnes** [comment]
I'm able to create files without issues.

@AlexiaDelorme Note that [these files](https://github.com/AlexiaDelorme/project-spacex/commit/c58672fab4001d87fa3935b9c0e59ac1f3a7d4ad) are not unnecessary, as they configure a working dev environment for Code Institute projects in Gitpod. Without these files, you get an unconfigured, clean Gitpod environment, without any of the configurations / extensions pre-installed by Code Institute.

**Comment by jankeromnes** [comment]
If someone has a workspace where this bug happens, could you please share a snapshot here?
- In the IDE top menu bar, there is a "Workspace" menu
- In that menu, there is a "Share Workspace Snapshot" item
- This will give you a snapshot URL, which can be used to start a clone of your workspace (which hopefully allows reproducing the bug)

**Comment by AlexiaDelorme** [comment]
@jankeromnes Thanks for getting back, I think I deleted them when I started working on my project, this is not what causing my issue I suppose.

**Comment by AlexiaDelorme** [comment]
@jankeromnes Yes, on my side I used the Code Institute template you mentioned in your previous comment, I think this is probably the case of most students reporting on this issue. 

Let me share the markdown button for my workspace snapshot: 
[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io/#snapshot/0b4a1c51-53a1-4f3d-98be-6902e18c9e5f)

It's not visible on the screenshot but on my side it's just the "format document" option that is no longer working when I right click on my file content to format it.

**Comment by jankeromnes** [comment]
> I think I deleted them when I started working on my project, this is not what causing my issue I suppose.

@AlexiaDelorme Good point, if it worked well before, but now not anymore, that's probably unrelated to the deleted files.

Still (on a side note), by removing the `.gitpod.yml`, you've uninstalled these VSCode extensions from Gitpod:
- `ms-python.python` (no more advanced Python linting / debugging)
- `formulahendry.auto-close-tag` (no more auto-closing HTML/XML tags)
- `mkaufman.HTMLHint` (no more advanced HTML linting)
- `eventyret.bootstrap-4-cdn-snippet` (no more `!bcdn`)

That's totally fine, just wanted to explain why some features may not be available for you even though they work for others.

> Let me share the markdown button for my workspace snapshot:

That's awesome, thank you so much. I'll see if this helps me reproduce the various problems mentioned above.

**Comment by AlexiaDelorme** [comment]
@jankeromnes Thanks! Indeed I think I'll add them back anyway, especially for the HTML closing tags :)

**Comment by jankeromnes** [comment]
In the provided snapshot, I'm able to create files & folders without issue:
- Use the "File" - "New File" menu
- Right-click "New File"
- Right-click "New Folder"

I'm also able to:
- Auto-complete HTML tags (but this is very basic, i.e. `<sp` can auto-complete to `<span`, but it doesn't auto-close the tag -- I guess that's because the `formulahendry.auto-close-tag` extension is not installed)
- Typing `.thisclass` and then `[Tab]` gives me `<div class="thisclass"></div>`
- Right-click "Format Document" (in HTML files, this can fix the indentation, but the feature is greyed out in Python files)
- Save files fast without issues

**Comment by AlexiaDelorme** [comment]
@jankeromnes Thanks a lot for checking, as you suggested I've added back the two files (.gitpod.yml & .gitpod.dockerfile) and I can now re-use the format command (either by right clicking or with the shortcut). This solved my issue, I don't know why the command stopped working only yesterday even though I deleted these files 3 months ago! Thanks a lot for your patience and I hope you'll be able to help the other students :)

**Comment by jankeromnes** [comment]
> Thanks a lot for checking, as you suggested I've added back the two files (.gitpod.yml & .gitpod.dockerfile) and I can now re-use the format command (either by right clicking or with the shortcut).

Wow, that's great news, thanks. Personally I've tried manually installing the Python extension into your workspace, but for some reason I still couldn't get `Format Document` to be re-enabled. I'm a bit puzzled by why this workspace behaves differently than brand new workspaces I create for other projects, so I'll continue investigating, but meanwhile it's super cool that your problem is now solved. 👍

> This solved my issue, I don't know why the command stopped working only yesterday even though I deleted these files 3 months ago!

That is a bit surprising to me as well. FYI, we've released an update to Gitpod yesterday (as we do about every 2 weeks), and in this update we've upgraded the IDE and a few built-in VSCode extensions. Maybe that had something to do with it? Not sure. Needs more investigation.

> Thanks a lot for your patience and I hope you'll be able to help the other students :)

You're very welcome! Sorry again for the awkward experience, and I also hope to be able to solve the other problems as well.

> This is the workspace I'm experiencing issues where I can't add a folder and I can't auto tag as well. Please help! Thanks!

Many thanks for the snapshot! Taking a look to see if I can finally reproduce this annoying bug.

**Comment by jankeromnes** [comment]
> I'm experiencing issues where I can't add a folder

@GlobetrotterG What folder are you trying to add, and where?

In your snapshot, I'm to right-click in the file explorer, then click "New Folder", then choose "test" as a name, and that works. It doesn't for you?

> and I can't auto tag as well

Now that I can reproduce. I see in your Extensions panel (in IDE left vertical bar) that `Auto Close Tag 0.5.6` is installed, but indeed typing `<span>` does not automatically add `</span>` behind (however, hitting `Ctrl+Space` after a `<span>` proposes to close the tag, but you probably expect that to happen automatically).

This could be a new bug in Theia, the IDE used by Gitpod. I'll investigate this further.

**Comment by jankeromnes** [comment]
Ha, now what's really strange: if I go into the Extensions panel, and uninstall the "Auto Close Tag" extension (and then click on the `Reload` button), I'm able to type `<p>` and the editor automatically adds `</p>` behind.

So maybe the "Auto Close Tag" extension conflicts with something that the IDE already does on its own?

**Comment by GlobetrotterG** [comment]
@jankeromnes - Thank you for looking into this. I was going to add a folder called 'CV' from 'assets' but it doesn't work for me. I tried using 'test' but no luck unfortunately. 

For the auto-tag, still no luck. Say for example, I use .class to auto tag a div, it still doesn't for me. 

Yes, I agree there's a bug in Theia, because it was fine a week ago.

**Comment by GlobetrotterG** [comment]
@jankeromnes - Thank you once again for your help and for showing me a video shot on Youtube. 

I might have to try and do a git commit and push to github and create a new workspace. I hope that works. I'll let you know. 

Thank you! :)

**Comment by jankeromnes** [comment]
@GlobetrotterG Well, I'm sorry about these awkward problems. I have a hard time understanding why you're getting them and I don't (after all, it's supposed to be a feature of Gitpod that we can all use the exact same coding environments and stop saying "it works on my machine"!)

What web browser are you using, by the way?

Also, please let me know if the fresh workspace also has that bug.

**Comment by GlobetrotterG** [comment]
@jankeromnes - That's absolutely fine, it's not your fault. I guess Gitpod is being temperamental on me! lol! I'm using Chrome browser.

**Comment by GlobetrotterG** [comment]
@jankeromnes - So I pushed this repo to my github and opened it as a different workspace, and it seems to be working fine now. I can add a folder and I can auto tag as well! 

Thank you for your help! You're a lifesaver! :)
