### ISSUE TITLE
Workspace not starting with feature preview enabled: cannot prepare for user namespaces

### ISSUE THREAD

**Issue by z3ky** [gitpod-io/gitpod#3102]
### Describe the bug

With feature preview enabled, workspaces don't start.
Gitpod 0.7.0b1, k3s v18
Internal registry

### Steps to reproduce
Enabled feature preview, start NextSimpleStarter

### Expected behavior
Workspace should start after pulling

### Additional information
` Warning   FailedToUpdateEndpoint   endpoints/ws-emerald-impala-xpeznzou-theia    Failed to update endpoint default/ws-emerald-impala-xpeznzou-theia: Operation cannot be fulfilled on endpoints "ws-emerald-impala-xpeznzou-theia": StorageError: invalid object, Code: 4, Key: /registry/services/endpoints/default/ws-emerald-impala-xpeznzou-theia, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: d16cbc93-b0a6-4064-8155-aaff3aad9fb0, UID in object meta:`

ws-manager:
``{"instanceId":"bfb48aa3-2671-48ae-9c17-fb4cb3435b37","level":"error","message":"workspace failed","serviceContext":{"service":"ws-manager","version":""},"severity":"ERROR","status":{"id":"bfb48aa3-2671-48ae-9c17-fb4cb3435b37","metadata":{"owner":"ea4688c3-f58c-4e6c-b2fb-9c7f7327f433","meta_id":"emerald-impala-xpeznzou","started_at":{"seconds":1612447769}},"spec":{"workspace_image":"registry.mydomain.com/workspace-images:dbb287492fd652568798cc5993eabfe8fab73f493d2dbb9b71d310cb2bbc3289","ide_image":"gcr.io/gitpod-io/self-hosted/ide/code:0.7.0-beta1","url":"https://emerald-impala-xpeznzou.ws.mydomain.com","timeout":"30m"},"phase":6,"conditions":{"failed":"cannot prepare for user namespaces: rpc error: code = DeadlineExceeded desc = context deadline exceeded","final_backup_complete":1},"repo":{"branch":"master","latest_commit":"ee6140753bf800ef00d900ec3e7a25a126061a5a"},"runtime":{"node_name":"mydomain"},"auth":{"owner_token":"\u0026J:_I_.UWf{SQg\u003e+Zg\u0026Z}PZ)((@j}UQ="}},"time":"2021-02-04T14:09:43Z","userId":"ea4688c3-f58c-4e6c-b2fb-9c7f7327f433","workspaceId":"emerald-impala-xpeznzou"}``

**Comment by stefanstoeckigt** [comment]
With feature preview enabled, workspaces don't start.
Gitpod 0.7.0b1, k3s v18
Internal registry

Getting a similar issue with external registry. 

```json
{
    "instanceId": "b3628310-4603-4f3d-b92b-ae36efe04ca1",
    "level": "error",
    "message": "workspace failed",
    "serviceContext": {
        "service": "ws-manager",
        "version": ""
    },
    "severity": "ERROR",
    "status": {
        "id": "b3628310-4603-4f3d-b92b-ae36efe04ca1",
        "metadata": {
            "owner": "2311269b-7056-4d07-8d1e-1835ca4e07d8",
            "meta_id": "aquamarine-sparrow-7sahyp68",
            "started_at": {
                "seconds": 1612448806
            }
        },
        "spec": {
            "workspace_image": "registry.gitlab.garrison.local/garrison.com/devops/deployment/gitpod/workspace-images:dbb287492fd652568798cc5993eabfe8fab73f493d2dbb9b71d310cb2bbc3289",
            "ide_image": "gcr.io/gitpod-io/self-hosted/ide/code:0.7.0-beta1",
            "url": "https://aquamarine-sparrow-7sahyp68.ws.gitpod.garrison.local",
            "timeout": "30m"
        },
        "phase": 2,
        "conditions": {
            "failed": "cannot pull image: rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 500 Internal Server Error",
            "deployed": 1
        },
        "runtime": {
            "node_name": "garblak8swkr01"
        },
        "auth": {
            "owner_token": "#sdNdOsO\u003eK)J9SJKsEI;L#aMEj|6keoq"
        }
    },
    "time": "2021-02-04T14:26:50Z",
    "userId": "2311269b-7056-4d07-8d1e-1835ca4e07d8",
    "workspaceId": "aquamarine-sparrow-7sahyp68"
}
```

**Comment by stefanstoeckigt** [comment]
@svenefftinge is there anything i can do locally to fix this issue?

**Comment by stefanstoeckigt** [comment]
Got the following log from the workspace pod

```json
{
    "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
    "error": "rpc error: code = DeadlineExceeded desc = context deadline exceeded",
    "level": "fatal",
    "message": "cannot prepare for user namespaces",
    "ring": 0,
    "serviceContext": {
        "service": "workspacekit",
        "version": ""
    },
    "severity": "CRITICAL",
    "time": "2021-02-05T11:17:57Z"
}
```

**Comment by davemecha** [comment]
We've got the same problem. We wanted to setup gitpod self hosted to try working with kubernetes in a more controlled environment but we don't get workspaces with feature preview started.

It'd be great to have any option to workaround this. Has anybody already succeeded with using feature preview on a self hosted gitpod environment?

**Comment by geropl** [comment]
There is a new SH-release: [v0.8.0](https://github.com/gitpod-io/gitpod/releases/tag/v0.8.0). That should fix all issues with workspacekit.

Could you try and close if it works? Thx!

**Comment by pkalemba** [comment]
For me is still not working im using v0.8.0

**Comment by asthomasdk** [comment]
I am also seeing this issue on 0.9.0-alpha1 using k3s v1.17.17+k3s1 on ubuntu 18.04.

**Comment by raghuP9** [comment]
> I am also seeing this issue on 0.9.0-alpha1 using k3s v1.17.17+k3s1 on ubuntu 18.04.

+1

Facing the same issue with 0.8.0 as well as 0.9.0-beta1 self-hosted installation with local registry.

**Node OS**: Ubuntu 20.04
**Kernel**:  5.4.0-72-generic
**K8s**: v1.17.9

`shiftfs` kernel module is loaded:

```bash
lsmod | grep -i shiftfs
   shiftfs                28672  0
```
 
`/dev/fuse` is also available inside `ws-daemon` containers.


Performed additional steps on nodes as specified in this docker [documentation](https://docs.docker.com/engine/install/linux-postinstall/#your-kernel-does-not-support-cgroup-swap-limit-capabilities) due to warnings appearing in docker logs.

**crashing workspace container logs**:

```json
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "error": "rpc error: code = DeadlineExceeded desc = context deadline exceeded",
  "level": "fatal",
  "message": "cannot prepare for user namespaces",
  "ring": 0,
  "serviceContext": {
    "service": "workspacekit",
    "version": ""
  },
  "severity": "CRITICAL",
  "time": "2021-05-11T20:52:36Z"
}
```

**ws-daemon container logs**:

```json
{
  "hooks": 2,
  "instanceId": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
  "level": "debug",
  "message": "running lifecycle hooks",
  "serviceContext": {
    "service": "ws-daemon",
    "version": ""
  },
  "severity": "DEBUG",
  "state": "ready",
  "time": "2021-05-11T20:51:37Z",
  "userId": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
  "workspaceId": "orange-urial-31t1854w"
}
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "ID": "863ce009cf346f8eec5535cff3484e5d8c12a983e9ca0b30b38e8833eeb2841b",
  "containerImage": "",
  "error": "not found\ngithub.com/containerd/containerd/errdefs.init\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.4.1/errdefs/errors.go:45\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6265\nruntime.doInit
\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6242\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6242\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6242\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/ru
ntime/proc.go:6242\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6242\nruntime.doInit\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:6242\nruntime.main\n\t/home/gitpod/sdk/go1.16/src/runtime/proc.go:208\nruntime.goexit\n\
t/home/gitpod/sdk/go1.16/src/runtime/asm_amd64.s:1371\ncontainer \"863ce009cf346f8eec5535cff3484e5d8c12a983e9ca0b30b38e8833eeb2841b\" in namespace \"k8s.io\"\ngithub.com/containerd/containerd/errdefs.FromGRPC\n\t/workspace/go/pkg/mod/gith
ub.com/containerd/containerd@v1.4.1/errdefs/grpc.go:107\ngithub.com/containerd/containerd.(*remoteContainers).Get\n\t/workspace/go/pkg/mod/github.com/containerd/containerd@v1.4.1/containerstore.go:50\ngithub.com/gitpod-io/gitpod/ws-daemon
/pkg/container.(*Containerd).handleContainerdEvent\n\t/tmp/build/components-ws-daemon--app.9a5485fb9729e803b6609f9e0c215f6c2ece44f0/pkg/container/containerd.go:167\ngithub.com/gitpod-io/gitpod/ws-daemon/pkg/container.(*Containerd).start\n
\t/tmp/build/components-ws-daemon--app.9a5485fb9729e803b6609f9e0c215f6c2ece44f0/pkg/container/containerd.go:150\nruntime.goexit\n\t/home/gitpod/sdk/go1.16/src/runtime/asm_amd64.s:1371",
  "level": "warning",
  "message": "cannot find container we just received a create event for",
  "serviceContext": {
    "service": "ws-daemon",
    "version": ""
  },
  "severity": "WARNING",
  "time": "2021-05-11T20:51:57Z"
}
{
  "@type": "type.googleapis.com/google.devtools.clouderrorreporting.v1beta1.ReportedErrorEvent",
  "error": "context deadline exceeded",
  "instanceId": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
  "level": "error",
  "message": "PrepareForUserNS: cannot find workspace container",
  "serviceContext": {
    "service": "ws-daemon",
    "version": ""
  },
  "severity": "ERROR",
  "time": "2021-05-11T20:52:07Z",
  "userId": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
  "workspaceId": "orange-urial-31t1854w"
}
```

**ws-manager container logs**:

```json
{
  "instanceId": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
  "level": "info",
  "message": "starting new workspace",
  "serviceContext": {
    "service": "ws-manager",
    "version": ""
  },
  "severity": "INFO",
  "time": "2021-05-11T20:51:34Z",
  "userId": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
  "workspaceId": "orange-urial-31t1854w"
}
{
  "instanceId": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
  "level": "error",
  "message": "workspace failed",
  "serviceContext": {
    "service": "ws-manager",
    "version": ""
  },
  "severity": "ERROR",
  "status": {
    "id": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
    "metadata": {
      "owner": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
      "meta_id": "orange-urial-31t1854w",
      "started_at": {
        "seconds": 1620766294
      }
    },
    "spec": {
      "workspace_image": "registry.raghu-gitpod.mydomain.com/workspace-images:e328e725d1813d384cc0f3e60094decf9b13a48a11c319a0e22f9b91994e35d5",
      "ide_image": "gcr.io/gitpod-io/self-hosted/ide/code:0.8.0",
      "url": "https://orange-urial-31t1854w.ws.raghu-gitpod.mydomain.com",
      "exposed_ports": [
        {
          "port": 3000,
          "visibility": 1,
          "url": "https://3000-orange-urial-31t1854w.ws.raghu-gitpod.mydomain.com"
        }
      ],
      "timeout": "30m"
    },
    "conditions": {
      "failed": "cannot prepare for user namespaces: rpc error: code = Internal desc = cannot find workspace container",
      "service_exists": 1,
      "deployed": 1
    },
    "runtime": {
      "node_name": "192.168.24.20",
      "pod_name": "ws-d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
      "node_ip": "192.168.24.20"
    },
    "auth": {
      "owner_token": "<REDACTED>"
    }
  },
  "time": "2021-05-11T20:52:07Z",
  "userId": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
  "workspaceId": "orange-urial-31t1854w"
}
{
  "instanceId": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
  "level": "error",
  "message": "workspace in UNKNOWN phase",
  "serviceContext": {
    "service": "ws-manager",
    "version": ""
  },
  "severity": "ERROR",
  "status": {
    "id": "d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
    "metadata": {
      "owner": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
      "meta_id": "orange-urial-31t1854w",
      "started_at": {
        "seconds": 1620766294
      }
    },
    "spec": {
      "workspace_image": "registry.raghu-gitpod.mydomain.com/workspace-images:e328e725d1813d384cc0f3e60094decf9b13a48a11c319a0e22f9b91994e35d5",
      "ide_image": "gcr.io/gitpod-io/self-hosted/ide/code:0.8.0",
      "url": "https://orange-urial-31t1854w.ws.raghu-gitpod.mydomain.com",
      "exposed_ports": [
        {
          "port": 3000,
          "visibility": 1,
          "url": "https://3000-orange-urial-31t1854w.ws.raghu-gitpod.mydomain.com"
        }
      ],
      "timeout": "30m"
    },
    "conditions": {
      "failed": "cannot prepare for user namespaces: rpc error: code = Internal desc = cannot find workspace container",
      "service_exists": 1,
      "deployed": 1
    },
    "runtime": {
      "node_name": "192.168.24.20",
      "pod_name": "ws-d4442f16-ccc0-4537-9cd5-a1e25e44d94a",
      "node_ip": "192.168.24.20"
    },
    "auth": {
      "owner_token": "<REDACTED>"
    }
  },
  "time": "2021-05-11T20:52:07Z",
  "userId": "30cef954-a97a-45dc-ab94-ed3ae02d1aba",
  "workspaceId": "orange-urial-31t1854w"
}
```

**Comment by stefanstoeckigt** [comment]
Has there been any update on this issue?

**Comment by stefanstoeckigt** [comment]
@geropl could we repo this issue?

**Comment by chaitu454** [comment]
HI All, I am facing the same issue with 0.9.0-alpha1 version of gitpod-self-hosting. Does any one have any fix for this issue already

**Comment by asthomasdk** [comment]
Just tested on alpha3 - and getting the same issue. 

"cannot prepare for user namespaces: rpc error: code = Internal desc = cannot mount shiftfs mark"

**Comment by stefanstoeckigt** [comment]
@asthomasdk  i am getting the same issue.

**Comment by corneliusludmann** [comment]
Hi @solomonope! Is this something you could have a look into / reproduce?

**Comment by z3ky** [comment]
I just tested a fresh installation of k3s 18 gitpod 0.9.0 alpha 3 on ubuntu with kernel v5 an shift fs enabled.
maybe enabling shift fs took me a step further, but I run into this:

`cannot prepare for user namespaces: rpc error: code = Internal desc = cannot find workspace container`

`17s         Warning   Unhealthy                 pod/ws-429fe953-7f5e-464f-ad02-43e223549929   Readiness probe failed: Get http://10.42.0.90:22999/_supervisor/v1/status/content/wait/true: dial tcp 10.42.0.90:22999: connect: connection refused`

`8s          Warning   FailedToUpdateEndpoint    endpoints/ws-coral-jaguar-mb9izedj-ports      Failed to update endpoint default/ws-coral-jaguar-mb9izedj-ports: Operation cannot be fulfilled on endpoints "ws-coral-jaguar-mb9izedj-ports": StorageError: invalid object, Code: 4, Key: /registry/services/endpoints/default/ws-coral-jaguar-mb9izedj-ports, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: 301ee548-501c-4a28-b74a-ce83b7404b6f, UID in object meta:`

**Comment by stefanstoeckigt** [comment]
Done anyone know what this error is related to, trying to get out a work around. As you can't disable the namespace feature in v0.9.0-alpha like you could in v0.8.0.

**Comment by rcdelacruz** [comment]
Got the same issue v0.9.0-alpha1 GCP self-hosted

**Comment by stefanstoeckigt** [comment]
Any progress on this?

**Comment by stefanstoeckigt** [comment]
This issue is still present on v0.9.0 self hosted.

**Comment by tomcastro** [comment]
Can confirm that this still happens on 0.9.0 self hosted on GCP/GKE cluster with Ubuntu with Containerd nodes. I tried SSHing into the nodes and it seems shiftfs is not enabled on their Ubuntu images.

**Comment by dtate-wave** [comment]
Ran into this issue as well when self hosting on GKE with GitPod version v0.9.0. Was able to work-around the issue by installing [shiftfs-dkms](https://github.com/toby63/shiftfs-dkms) through a daemonset on my GKE cluster.

As noted in the shiftfs-dkms module, "shiftfs will still be supported for older kernels until approximately April 2022". Is there an ETA when there will be an official replacement of shiftfs in GitPod?

Daemonset: https://gist.github.com/dtate-wave/9406346fd42f1c1e1f20e02390e6396d

**Comment by ghuntley** [comment]
👋 Could folks within this issue:

1. Come join https://www.gitpod.io/chat in the #gitpod-self-hosted room.
2. Try again with v0.10.0 and report back with their experiences.

**Comment by jgallucci32** [comment]
Has everyone on this thread tried adding the following to `answers.yaml` to run the init container which enables the shiftfs module for Ubuntu-based container hosts?
```yaml
    wsDaemon:
      userNamespaces:
        shiftfsModuleLoader:
          enabled: true
```
It is disabled by default as it assumes the `shiftfs` module is already loaded on your container host. When enabled, an initi container is added to `ws-daemon` which installs the kernel module into the host and enables it.

**Comment by hm2075** [comment]
same issue on centos8,     worked fine on 0.5.0,  thought I would revist gitpod  and got more or less everything working and then cant start workspace

**Comment by jgallucci32** [comment]
> same issue on centos8, worked fine on 0.5.0, thought I would revist gitpod and got more or less everything working and then cant start workspace

@hm2075 I made some progress with RHEL 8. I found out the `shiftfs` module is only compatible with Ubuntu so you have to use the `fuse-overlayfs` module by setting this value in answers.yaml:
```yaml
    wsDaemon:
      userNamespaces:
        fsShift: fuse
```
When you install `docker-ce` on RHEL 8 it will install `fuse-overlayfs` as a dependency. Additionally you must configure Docker to use `k8s.io` as the default workspace, as gitpod is looking for workspaces in that namespace (I believe it's hard-coded). You can do this by running the following:
```
cat << EOF > /etc/docker/daemon.json
{
  "containerd-namespace": "k8s.io"
}
EOF
```
Having said all of this, I am still stuck in the same spot (workspace will not start) but I have been able to remove a lot of the errors leading up to the point of creating the workspace. I'm currently stuck in "running lifecycle hooks" stage of setting up the workspace.
