### ISSUE TITLE
Ports close after a time

### ISSUE THREAD

**Issue by joshleblanc** [gitpod-io/gitpod#439]
**Describe the bug**
Working on a project with an exposed port. At some time, I start seeing a screen telling me the port is not exposed, and to check my .gitpod.yml file.

**To Reproduce**
Unsure. Happens seemingly randomly. Restarting the container fixes it, however.

**Expected behavior**
Once a port is exposed, it should stay exposed. I suppose.

**Comment by svenefftinge** [comment]
Interesting, haven't seen that or heard from anyone.
Can you share a project with which it happens?

**Comment by jankeromnes** [comment]
Actually, I think the wording of that error screen is wrong. The problem isn't that the port is not exposed, but that nothing is currently running on the exposed port.

The solution is not to check your `.gitpod.yml` file (as the error screen currently says), but to make sure the server is actually running. We should fix this error screen (and also, the error screen should not redirect away, and it should auto-refresh every 5s to check if the requested app or server is back online).

**Comment by meysholdt** [comment]
I very much like Jan's proposal. 

As a workaround, it's already possible to open the "Ports" view in Gitpod and see of some program listens on that port.

**Comment by HorizonShadow** [comment]
The server is actually running. Restarting the server doesn't fix the problem. I should have put that in my original post.

I'll take some screenshots next time it happens.

**Comment by HorizonShadow** [comment]
This about sums it up

![image](https://user-images.githubusercontent.com/1729810/55672347-5a88b180-5870-11e9-965f-e8d014cec2b2.png)

**Comment by svenefftinge** [comment]
Can we reproduce it with this project?
https://github.com/HorizonShadow/hyperstack-test

**Comment by HorizonShadow** [comment]
Go for it. It’s inconsistent. In the screenshot, the web process is clearly running, and the URL isn’t working. I think some of the times I’ve experienced it, the web process had just crashed. 

Could well just be hyperstack and not gitpod

**Comment by HorizonShadow** [comment]
‘foreman start’ to run

**Comment by jankeromnes** [comment]
Could it be that "web process just crashed" followed by "reload preview" showed you the error page once, and that since the error page is redirected away, even when the server resumes and you reload the error page, it stays the same?

**Comment by geropl** [comment]
@HorizonShadow Could it be that it is a problem with `foreman`? Do not know anything about it, but had simmilar problems [here](https://github.com/gitpod-io/gitpod/issues/435#issuecomment-481176240): A process behind it would not receive packages at all.

**Comment by HorizonShadow** [comment]
@geropl It could be, however with my monkey patches, the hot-reloader + web server both work behind foreman. (Well, most of the time). I have noticed one or the other will hang sometimes, as described in that issue.
