### ISSUE TITLE
can't delete workspace after failed docker build

### ISSUE THREAD

**Issue by anudeepreddy** [gitpod-io/gitpod#635]
**Describe the bug**
can't delete workspace after failed docker build

![image](https://user-images.githubusercontent.com/6022231/60023327-38564100-96b3-11e9-99b6-fec6ec59b51b.png)

## contents of .gitpod.dockerfile:

```
FROM gitpod/workspace-full
USER gitpod
RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list \
    && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key --keyring /usr/share/keyrings/cloud.google.gpg add - \
    && sudo apt-get update && sudo apt-get install google-cloud-sdk
```

**To Reproduce**
Create a workspace which fails to build

**Expected behavior**
The workspace should be deleted from the dashboard

**Comment by techwithtim** [comment]
**Experiencing the same issue**

**Comment by jankeromnes** [comment]
Even worse, apparently these failed workspaces don't have a `Stop` button, but still count toward your limit of 8 workspaces actively running in parallel. So if you have 8 of these failed builds, you're essentially forbidden from creating new workspaces and have to wait for 1.5 hours for the situation to resolve itself.

See https://github.com/techwithtim/Sudoku-GUI-Solver/pull/1#issuecomment-505584281 for a better explanation.

Cc @32leaves would you know more about how this could be fixed?

**Comment by jankeromnes** [comment]
So, we believe that it's the same bug as https://github.com/gitpod-io/gitpod/issues/644, and we have a fix that's awaiting deployment (hopefully today or tomorrow).

If our theory is right, the fix should also allow deleting failed workspaces.

**Comment by jankeromnes** [comment]
#644 has been resolved, and the fix has been deployed!

You can now have failing Docker builds more than 8 times in rapid succession (e.g. with https://gitpod.io/#https://github.com/jankeromnes/gitpod-test ), and they can then be deleted without issues. 🎉

**Comment by anudeepreddy** [comment]
Hey,
While working on a repository I faced this issue.

![image](https://user-images.githubusercontent.com/6022231/63634261-88c92b00-c671-11e9-9e82-45315757c017.png)

It gives me a message to contact while deleting workspaces which failed to build but then when i reload the page the workspaces are deleted

**Comment by jankeromnes** [comment]
@anudeepreddy Could you please try again? This looks similar to https://github.com/gitpod-io/gitpod/issues/744 which recently got resolved.

**Comment by svenefftinge** [comment]
I see this still happening (on dev-staging) with workspaces that are not in Stopped mode (i.e. failed in Pending).

**Comment by j-elmer123** [comment]
Got the same issue, and I have a workspace with more than one day old and cannot be deleted after I press delete button. Not sure what should I do. :thinking:

**Comment by axonasif** [comment]
Hi @j-elmer123, it's possibly related with https://github.com/gitpod-io/gitpod/issues/8274

**Comment by j-elmer123** [comment]
> Hi @j-elmer123, it's possibly related with #8274

Hi @axonasif thank you for the reply. It seems not because of out of memory, but because of the incorrect shell command that I put inside `.gitpod.dockerfile`

Here is the command inside my dockerfile
```Dockerfile
FROM gitpod/workspace-postgres

RUN sudo apt update && \
  sudo apt upgrade -y && \
  sudo apt install -y snapd nodejs ruby-full openjdk-11-jdk && \
  npm install -g yarn -y && \
  sudo apt update

RUN sudo snap install androidsdk
```

And here is the result after I look into the console
![gitpod-error](https://user-images.githubusercontent.com/8566597/184570510-8f41fc74-ffd7-433a-80a1-2ebb5ff6c8d9.png)

**Comment by fahrulseptiana** [comment]
Experiencing the same issue, and it's been a day.

I have two failed workspace and I cant delete it.

![image](https://user-images.githubusercontent.com/10472373/185528374-9e50965e-3a2b-4baf-9e90-01b72e971482.png)
