### ISSUE TITLE
Incorrect offline message

### ISSUE THREAD

**Issue by JesterOrNot** [gitpod-io/gitpod#789]
**Describe the bug**
Sometimes when opening a workspace or while working you will get the offline thing and will be rendered unable to make changes despite in fact being online
![Screenshot 2019-09-13 at 2 17 03 PM](https://user-images.githubusercontent.com/50386709/64890781-027f8380-d636-11e9-8e5e-c902b890a2e7.png)
![Screenshot 2019-09-13 at 2 16 49 PM](https://user-images.githubusercontent.com/50386709/64890783-03181a00-d636-11e9-8388-d749d038cc2e.png)

**To Reproduce**
Seems to be random unsure how to reproduce one trend I noticed is it occurs often when opening files another one is that starting a workspace also seems to trigger it
If it helps here is the link to the repo https://gitpod.io/#https://github.com/JesterOrNot/VoiceID
Some notes:
September-13th-2019 3:01 pm central time> Went offline and back online twice in 3 seconds while still online
September-13th-2019 3:09 pm central time> Went offline and back online twice while deploying IntelliSense extension
September-13th-2019 3:16 pm central time> Went offline when committing a change with the source control manager
September-13th-2019 3:22 pm central time> Went offline when pushing a change to Github
September-16th-2019 7:37 am central time> Went offline when switching current viewed file to config.yml
September 18th 2019 7:50 central time> Went offline when working normally
September 27th 2019 7:43 central time> Went offline on workspace start no extensions installed
**Expected behavior**
Being able to continue working

**Comment by jankeromnes** [comment]
Hi @JesterOrNot, sorry about this issue. The orange bottom bar generally indicates WebSocket problems, which can have various causes:

> 1. the network is slow/unreliable
> 2. the front-end’s event loop is blocked by a long-running script
> 3. the backend container is slow to respond

(From https://github.com/gitpod-io/gitpod/issues/770#issuecomment-529109695)

Also, we've recently noticed that some VS Code extensions are very "chatty", causing some pressure on the WebSocket connection because they send many meta-data back-and-forth.

We're currently looking into optimizing the extensions' communication via WebSocket, which will hopefully reduce the frequency of these annoying "offline" indicators.

**Comment by JesterOrNot** [comment]
is there any other way besides reporting more incidents to help with the issue?

**Comment by svenefftinge** [comment]
We have fixed it already and will deploy it on Monday.

**Comment by JesterOrNot** [comment]
Yay!

**Comment by JesterOrNot** [comment]
Should we close this issue?a

**Comment by jankeromnes** [comment]
Unfortunately, the fix is still not deployed. We tried to deploy it this morning, but it failed and caused some DB issues (which are now resolved).

Let's close this issue once the fix was successfully deployed. 🙂 🤞

**Comment by JesterOrNot** [comment]
Alright, so you'll close it once it is deployed?

**Comment by jankeromnes** [comment]
Yes! And it was actually deployed 2 hours ago. 🎉

Now we can finally close this issue. 🙌 But please re-open it if the problem comes back.
