### ISSUE TITLE
I/O throttles content-init and maybe backups

### ISSUE THREAD

**Issue by kylos101** [gitpod-io/gitpod#9276]
### Bug description

Workspace start is slow when using [iolimits](https://github.com/gitpod-io/gitpod/blob/7853926dc05603503a964580e1aedb29ffa8b0e8/install/installer/pkg/components/ws-daemon/configmap.go#L110), we think this is because `content-init` is being i/o limited.

We're unsure if backups are being limited. 

### Steps to reproduce

Try starting a workspace in a cluster where iolimit is defined in the configmap for ws-daemon.

### Workspace affected

n/a

### Expected behavior

Ideally we would not throttle workspaces on content-init or backup.

### Example repository

n/a

### Anything else?

I/O limiting was introduced [here](https://github.com/gitpod-io/gitpod/pull/9271).

**Comment by utam0k** [comment]
First of all, The custom limitation of the cgroup depends on the life cycle of the pod, making it difficult to control the timing. But we have some cgroup group, `container`/`worksapce`/`user`. 
```console
<container-cgorup>  drwxr-xr-x 3 root      root
 └── workspace      drwxr-xr-x 5 gitpodUid gitpodGid
   └── user         drwxr-xr-x 5 gitpodUid gitpodGid
```

We are currently applying restrictions to container cgroups. It means all processes in the workspace are limited. 

I know timing is difficult to control but thought it might be smart to separate by the process. A user-run process should be sufficient to apply the restrictions. Other `content-init`, etc. should belong to the `workspace` cgroup, and these custom cgroup restrictions should apply to the `user` cgroup, which should solve these problems cleanly.

**Comment by utam0k** [comment]
Relates codes.
https://github.com/gitpod-io/gitpod/blob/70d832b5a93c51f416030c9a9c2d4116c2389dad/components/ws-daemon/pkg/iws/iws.go#L372-L379

**Comment by kylos101** [comment]
@aledbf are we still throttling content-init when using iolimits?

For example, I'm unsure if it was resolved by:
https://github.com/gitpod-io/gitpod/pull/9309 or https://github.com/gitpod-io/gitpod/pull/9309

I ask to see if it is something @utam0k should focus on tomorrow or not. Otherwise his next priority is the .NET issue.

**Comment by csweichel** [comment]
I still don't see how this should be the case. `io.max` is written to the cgroup of the workspace pod. Content init happens in the process tree of ws-daemon which cannot be subject to those limits.

**Comment by atduarte** [comment]
Since IO limits were not working, do we still believe content-init and backups IO was throttled?

**Comment by kylos101** [comment]
Closing this. [[1](https://github.com/gitpod-io/gitpod/issues/9276#issuecomment-1099201642)] 

Plus, we're actively working on IO limiting [here](https://github.com/gitpod-io/gitpod/issues/9406).
