### ISSUE TITLE
Issues accessing Fastly endpoints from within docker that runs in Gitpod

### ISSUE THREAD

**Issue by shaal** [gitpod-io/gitpod#9354]
### Bug description

Issues accessing Fastly endpoints from within docker that runs in Gitpod

When running `curl https://www.drupal.org/files/issues/2020-03-30/2759397-25.patch -vvv`, I am getting -
```
*   Trying 151.101.2.217:443...
* Connected to www.drupal.org (151.101.2.217) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
```
And then it hangs for a minute, and display
```
* OpenSSL SSL_connect: Connection reset by peer in connection to www.drupal.org:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: Connection reset by peer in connection to www.drupal.org:443
```

### Steps to reproduce

* Open any Gitpod workspace (tested in US Gitpod workspace)
* Confirm 10 times that you can run `curl https://www.fastly.com` with no issues ✅ 
* `docker run -it debian:11`
* `apt update`
* `apt install curl -y`
* Confirm 10 times that you can run `curl https://www.fastly.com` with no issues

You'll notice that inside docker, sometimes it works perfect, and sometimes it just hang up

### Anything else?

(This was found because of new errors when running composer requests to drupal.org (which uses Fastly CDN) through DrupalPod.

This might be a temporary Fastly issue? but it's weird why I cannot replicate this in Gitpod itself (not inside docker inside Gitpod), nor I can replicate that on local machine with or without Docker.

**Comment by shaal** [comment]
@misterfalcon posted this on Gitpod Discord, not sure if it's related or not -
https://discord.com/channels/816244985187008514/839379835662368768/964597530648252476
```
have a question that I also sent to support, but maybe someone here has some insight....
Outbound connections to google over https are not working all of a sudden (starting today) from within our docker
containers. These same docker containers are also running on EC2 instances that we manage and have setup through a
CI/CD pipeline, so effectively the same setup. We are not having any issues on our EC2 instances so we suspect there's
something going on with Gitpod. Yesterday we had no issues, and today we did with no change to our code or config.

These are strictly issues reaching google, which affects our API since that relies on making external calls to Firebase. All
outbound calls to google from our container are hanging on TLS handshake OUT. We tested this by calling curl -v
https://www.google.com/ from within our container.

Any ideas?
```

**Comment by motiapp** [comment]
We think this is a Docker config issue on Gitpod's end relating to DNS resolution. Running `cat /etc/resolv.conf` in the container returns:
**nameserver 127.0.0.11
options ndots:0**

When running on our EC2 instance we get:
**search ec2.internal
nameserver 127.0.0.11
options edns0 trust-ad ndots:0**

From what I've read Docker is supposed to mirror **/etc/resolve.conf** from the host machine to the container when the container starts up. The host machine in a gitpod workspace reports a good config:
**nameserver 1.1.1.1
nameserver 8.8.8.8**

**Comment by aledbf** [comment]
@motiapp what container are you using to get that output (I cannot reproduce the error)

**Comment by motiapp** [comment]
> @motiapp what container are you using to get that output (I cannot reproduce the error)

These are containers we setup in our repo and that get prebuilt and run when the workspace starts up.

**Comment by shaal** [comment]
This problem was partially fixed by https://github.com/gitpod-io/gitpod/pull/9356, now it doesn't happen in Docker.
But project that use `docker-compose`, still have the same issue.

It wasn't like that before today.

**Comment by motiapp** [comment]
We also are using `docker-compose`, and still seeing the issue. What makes no sense to me is I can get good responses from all sorts of sites using curl inside the container, except google.

**Comment by motiapp** [comment]
Here's a repo you can use to prove the failure I'm seeing:
https://github.com/motiapp/docker-test

**Comment by shaal** [comment]
According to @aledbf, this is a side effect of removing slirp4netns https://github.com/gitpod-io/gitpod/pull/8955#issuecomment-1091095660

A fix for docker was implemented yesterday, https://github.com/gitpod-io/gitpod/pull/9356

But it doesn't solve the problem for projects that use `docker-compose`, because docker-compose does not follow the value from dockerd. 

A solution/workaround for docker-compose is being worked on here -
https://github.com/gitpod-io/gitpod/pull/9360

In the meantime, on the project level it can be solved by adding this docker-compose yaml file:
```yaml
networks:                                
  default:                               
    driver_opts:                         
      com.docker.network.driver.mtu: 1440
```

**Comment by motiapp** [comment]
Excellent! I can confirm the network config works for me.

**Comment by aledbf** [comment]
Closing. Fixed by #9360 and #9356

@motiapp please open a workspace and run `docker-compose version` 
Should return `Docker Compose version v2.4.1.2-gitpod`.

No change is required to the `docker-compose` yaml file.

**Comment by motiapp** [comment]
@aledbf confirmed, thanks!

**Comment by perlun** [comment]
Thanks for this issue. :pray: It helped us track down MTU-related issues with running Docker on Hetzner private networks, where the MTU is smaller than the standard 1500. Interestingly enough, Fastly-based URLs was the common denominator in the problems we were seeing as well. Here's the MTU sizes for the machine:

```
root@runner-tyx4pz5q-gitlab-docker-machine-1680497999-5f2d58f2:~# ip addr | grep mtu
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
2: enp7s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
6: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default ```

More details in case anyone else is seeing something similar:

* https://bascht.com/tech/2021/04/08/kubernetes-docker-dind-mtu-issues-on-hetzner-cloud/
* https://mlohr.com/docker-mtu/ (the fix in this blog post was exactly what was needed in our use case :tada:)

**Comment by VuiDJi** [comment]
This issue is still relevant with Docker v26.1.4 and Docker Compose v2.27.1, and also with the Fastly network (intermittent access issues to GitHub), showing the error: "Fastly error: unknown domain: github.com. Please check that this domain has been added to a service."
I hope the provided workaround helps.

**Comment by VuiDJi** [comment]
No, unfortunately it still doesn't work.
<img width="515" alt="image" src="https://github.com/gitpod-io/gitpod/assets/44698/34c8bf2e-bef5-4401-8764-476ca34ce8e7">

**Comment by axonasif** [comment]
Hi @VuiDJi, how can we reproduce this?
